using System.IO;
using System.Text.Json;
using KawaiiIsland.Services;

namespace KawaiiIsland.Tests;

public sealed class WidgetTests
{
    [Theory]
    [InlineData("Spotify", "SpotifyAB.SpotifyMusic_zpdnekdrzrea0!Spotify", true)]
    [InlineData("Uninstall Zoom", @"C:\Zoom\uninstall.exe", false)]
    [InlineData("Java Uninstaller", "Microsoft.AutoGenerated.{X}", false)]
    [InlineData("Python Manuals", @"C:\Python\Doc\python.chm", false)]
    [InlineData("Website", @"C:\links\site.url", false)]
    public void Start_menu_list_keeps_apps_only(string name, string id, bool keep) => Assert.Equal(keep, AppCatalog.IsApp(name, id));

    [Fact]
    public void Store_apps_pin_by_appsfolder_path_without_duplicates()
    {
        var items = new List<ShortcutItem>();
        var app = new InstalledApp("Spotify", "SpotifyAB.SpotifyMusic_zpdnekdrzrea0!Spotify");
        Assert.Equal(PinResult.Added, ShortcutLauncher.PinApp(items, app, max: 8));
        Assert.Equal(@"shell:AppsFolder\SpotifyAB.SpotifyMusic_zpdnekdrzrea0!Spotify", items[0].Path);
        Assert.Equal(PinResult.AlreadyPinned, ShortcutLauncher.PinApp(items, app, max: 8));
    }

    [Fact]
    public void Open_meteo_current_weather_parses()
    {
        using var doc = JsonDocument.Parse("""{ "current": { "time": "2026-10-01T12:00", "temperature_2m": 21.4, "weather_code": 2 } }""");
        var w = WeatherService.ParseCurrent(doc.RootElement, "Bloomington", fahrenheit: false)!;
        Assert.Equal("21°", w.Text);
        Assert.Equal("⛅", w.Symbol);
        Assert.Equal("Partly cloudy", w.Condition);
        using var empty = JsonDocument.Parse("{}");
        Assert.Null(WeatherService.ParseCurrent(empty.RootElement, "x", false));
    }

    [Theory]
    [InlineData(0, "☀")]
    [InlineData(63, "☂")]
    [InlineData(81, "☂")]
    [InlineData(73, "❄")]
    [InlineData(96, "⚡")]
    [InlineData(45, "≋")]
    public void Weather_codes_map_to_symbols(int code, string symbol) => Assert.Equal(symbol, WeatherCodes.Symbol(code));

    [Theory]
    [InlineData(44, false, "\uE854")]
    [InlineData(100, false, "\uE83F")]
    [InlineData(5, false, "\uE850")]
    [InlineData(60, true, "\uE83E")]
    public void Battery_glyph_follows_level(int percent, bool charging, string glyph) =>
        Assert.Equal(glyph, IslandWindow.BatteryGlyph(percent, charging));
}

public sealed class AppCatalogLiveTests
{
    /// <summary>Reads the real Start menu (like the picker does, on an STA thread). Every Windows install has apps.</summary>
    [Fact]
    public void Lists_installed_start_menu_apps()
    {
        List<InstalledApp> apps = [];
        int icons = 0;
        var dir = Path.Combine(Path.GetTempPath(), "kawaii-icons-" + Guid.NewGuid().ToString("N"));
        var thread = new Thread(() =>
        {
            apps = AppCatalog.All();
            icons = apps.Take(10).Count(a => ShortcutLauncher.Icon(a.Path, dir) is not null);
        });
        thread.SetApartmentState(ApartmentState.STA);
        thread.Start();
        thread.Join();
        Assert.NotEmpty(apps);
        Assert.DoesNotContain(apps, a => a.Name.StartsWith("Uninstall", StringComparison.OrdinalIgnoreCase));
        Assert.All(apps, a => Assert.StartsWith(@"shell:AppsFolder\", a.Path));
        Assert.True(icons >= 8, $"only {icons}/10 app icons extracted");
    }
}
