// Exports every mascot skin x expression (plus the box form):
//   design/mascot/*.svg                                   — source art
//   windows/src/KawaiiIsland/Assets/Mascots.xaml          — WPF DrawingImages keyed "Mascot.<skin>.<expr>"
// Run: node gen.mjs
import { writeFileSync, readdirSync, unlinkSync } from 'node:fs';
import { createRequire } from 'node:module';
const { face, layers, svg, box, SKINS, EXPRESSIONS, TRACKING } = createRequire(import.meta.url)('./mascot.js');

const dir = new URL('./', import.meta.url);
const all = {};
for (const skin of Object.keys(SKINS)) for (const ex of EXPRESSIONS) {
  all[`${skin}.${ex}`] = face(skin, ex);
  all[`${skin}.${ex}.code`] = face(skin, ex, 'code'); // coding / lock-in outfit
}
all['box.open'] = box(true); all['box.closed'] = box(false);

for (const f of readdirSync(dir)) if (f.endsWith('.svg')) unlinkSync(new URL(f, dir));
for (const [k, svg] of Object.entries(all)) writeFileSync(new URL(`${k.replaceAll('.', '-')}.svg`, dir), svg.replace('<svg ', '<svg width="64" height="64" ') + '\n');

// --- SVG subset -> WPF DrawingGroup (ellipse, circle, rect, path, g; fill/stroke/opacity/rotate) ---
const attrs = s => Object.fromEntries([...s.matchAll(/([\w-]+)="([^"]*)"/g)].map(m => [m[1], m[2]]));
const rotate = a => { const m = /rotate\(([-\d.]+) ([-\d.]+) ([-\d.]+)\)/.exec(a.transform || ''); return m ? `<RotateTransform Angle="${m[1]}" CenterX="${m[2]}" CenterY="${m[3]}"/>` : ''; };
function geometry(tag, a) {
  const t = rotate(a), wrap = (el, open) => t ? `${open}><${el}.Transform>${t}</${el}.Transform></${el}>` : `${open}/>`;
  if (tag === 'ellipse') return wrap('EllipseGeometry', `<EllipseGeometry Center="${a.cx},${a.cy}" RadiusX="${a.rx}" RadiusY="${a.ry}"`);
  if (tag === 'circle') return wrap('EllipseGeometry', `<EllipseGeometry Center="${a.cx},${a.cy}" RadiusX="${a.r}" RadiusY="${a.r}"`);
  if (tag === 'rect') return wrap('RectangleGeometry', `<RectangleGeometry Rect="${a.x},${a.y},${a.width},${a.height}" RadiusX="${a.rx || 0}" RadiusY="${a.rx || 0}"`);
  if (tag === 'path') return wrap('PathGeometry', `<PathGeometry Figures="${a.d.trim()}"`);
  throw new Error(`unsupported <${tag}>`);
}
function drawing(tag, a) {
  const fill = a.fill && a.fill !== 'none' ? ` Brush="${a.fill}"` : '';
  const cap = a['stroke-linecap'] === 'round' ? ' StartLineCap="Round" EndLineCap="Round"' : '';
  const join = a['stroke-linejoin'] === 'round' ? ' LineJoin="Round"' : '';
  const pen = a.stroke ? `<GeometryDrawing.Pen><Pen Brush="${a.stroke}" Thickness="${a['stroke-width'] || 1}"${cap}${join}/></GeometryDrawing.Pen>` : '';
  const g = `<GeometryDrawing${fill}>${pen}<GeometryDrawing.Geometry>${geometry(tag, a)}</GeometryDrawing.Geometry></GeometryDrawing>`;
  return a.opacity ? `<DrawingGroup Opacity="${a.opacity}">${g}</DrawingGroup>` : g;
}
function toXaml(svg) {
  const out = ['<GeometryDrawing Brush="Transparent" Geometry="M0,0 H64 V64 H0 Z"/>']; // fixed 64x64 bounds so expressions never shift
  const stack = [{}];
  for (const [, close, tag, rest] of svg.matchAll(/<(\/?)(\w+)([^>]*?)\/?>/g)) {
    if (tag === 'svg') continue;
    if (tag === 'g') { close ? stack.pop() : stack.push({ ...stack.at(-1), ...attrs(rest) }); continue; }
    if (!close) out.push(drawing(tag, { ...stack.at(-1), ...attrs(rest) }));
  }
  return out.join('');
}
// Eye-tracking layers (round-eyed expressions only): Mascot.<skin>.<expr>[.code].under|eyes|over as DrawingGroups.
const parts = {};
for (const skin of Object.keys(SKINS)) for (const ex of TRACKING) for (const outfit of ['', 'code'])
  for (const [layer, body] of Object.entries(layers(skin, ex, outfit)))
    parts[`${skin}.${ex}${outfit ? '.' + outfit : ''}.${layer}`] = svg(body);

const xaml = `<!-- GENERATED by design/mascot/gen.mjs from mascot.js — do not edit by hand. -->
<ResourceDictionary xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation" xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml">
${Object.entries(all).map(([k, svg]) => `  <DrawingImage x:Key="Mascot.${k}"><DrawingImage.Drawing><DrawingGroup>${toXaml(svg)}</DrawingGroup></DrawingImage.Drawing></DrawingImage>`).join('\n')}
${Object.entries(parts).map(([k, s]) => `  <DrawingGroup x:Key="Mascot.${k}">${toXaml(s)}</DrawingGroup>`).join('\n')}
</ResourceDictionary>
`;
writeFileSync(new URL('../../windows/src/KawaiiIsland/Assets/Mascots.xaml', dir), xaml);
console.log(`${Object.keys(all).length} mascot images -> SVG + Mascots.xaml`);
